SET(CPLEX_ROOT_DIR "/opt/ibm/ILOG/CPLEX_Studio1251/cplex/" CACHE PATH "cplex root directory")
SET(CONCERT_ROOT_DIR "/opt/ibm/ILOG/CPLEX_Studio1251/concert/" CACHE PATH "concert root directory")

FIND_PATH(CPLEX_INCLUDE_DIR ilcplex/cplex.h HINTS ${CPLEX_ROOT_DIR}/include)
FIND_PATH(CONCERT_INCLUDE_DIR ilconcert/iloenv.h HINTS ${CONCERT_ROOT_DIR}/include)

FIND_PATH(CPLEX_BIN_DIR libcplex1251.so HINTS ${CPLEX_ROOT_DIR}/bin/x86-64_sles10_4.1)

FIND_LIBRARY(CPLEX_LIBRARY_RELEASE cplex HINTS ${CPLEX_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic)
FIND_LIBRARY(CPLEX_LIBRARY_DEBUG cplex HINTS ${CPLEX_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic)
set(CPLEX_LIBRARY "optimized;${CPLEX_LIBRARY_RELEASE};debug;${CPLEX_LIBRARY_DEBUG}")

FIND_LIBRARY(ILOCPLEX_LIBRARY_RELEASE ilocplex HINTS ${CPLEX_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic)
FIND_LIBRARY(ILOCPLEX_LIBRARY_DEBUG ilocplex HINTS ${CPLEX_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic)
set(ILOCPLEX_LIBRARY "optimized;${ILOCPLEX_LIBRARY_RELEASE};debug;${ILOCPLEX_LIBRARY_DEBUG}")

FIND_LIBRARY(CONCERT_LIBRARY_RELEASE concert HINTS ${CONCERT_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic/)
FIND_LIBRARY(CONCERT_LIBRARY_DEBUG concert HINTS ${CONCERT_ROOT_DIR}/lib/x86-64_sles10_4.1/static_pic/)
set(CONCERT_LIBRARY "optimized;${CONCERT_LIBRARY_RELEASE};debug;${CONCERT_LIBRARY_DEBUG}")

IF(CPLEX_LIBRARY AND ILOCPLEX_LIBRARY AND CONCERT_LIBRARY)
   SET(CPLEX_FOUND TRUE)
   MESSAGE(STATUS "Cplex found.")
ELSE()
   MESSAGE("Cplex NOT found.")
ENDIF()

## ILPCC
set(ILPCC_INCLUDE_DIR /home/markus/workspace/ILPCC/include/)
